export const CACHE_KEYS = {
  INJURY_TYPES: 'CACHE_INJURY_TYPES',
  INJURY_SIDES: 'CACHE_INJURY_SIDES',
  INJURY_REASONS: 'CACHE_INJURY_REASONS',
  MEDICAL_PROGRAMS: 'CACHE_MEDICAL_PROGRAMS',
  INDUSTRIAL_PARTS: 'INDUSTRIAL_PARTS',

} as const;
